const data = [
    {
        category: 'Grocery',
        items: [
          {
            id: 1,
            name: 'Mother Dairy Classic',
            weight: '400g',
            price: 400,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/86446a.jpg?ts=1641540332',
            amount: 1,
          },
          {
            id: 2,
            name: 'Nestle Milkmaid Sweetened...',
            weight: '380g',
            price: 147,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/10491a.jpg',
            amount: 1,
          },
          {
            id: 3,
            name: 'Table White Egg- 30 Pieces Tray',
            weight: '30 Pieces',
            price: 196,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/483705a.jpg?ts=1657805510',
            amount: 1,
          },
          {
            id: 4,
            name: 'Harvest Gold Hearty Brown',
            weight: '400g',
            price: 400,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/24194a.jpg?ts=1661157751',
            amount: 1,
          },
          {
            id: 5,
            name: 'Mother Dairy Paneer',
            weight: '200g',
            price: 90,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/192a.jpg?ts=1644908944',
            amount: 1,
          },
          {
            id: 6,
            name: 'Amul Salted Butter',
            weight: '500g',
            price: 275,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/160a.jpg?ts=1654778815',
            amount: 1,
          },
          {
            id: 7,
            name: 'Amul Salted Masti Curd',
            weight: '400g',
            price: 43,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/45533a.jpg?ts=1654845569',
            amount: 1,
          },
          {
            id: 8,
            name: 'Harvest Gold White Bread',
            weight: '400g',
            price: 400,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/448095a.jpg?ts=1661157752',
            amount: 1,
          },
          {
            id: 9,
            name: 'Mother Dairy Classic ',
            weight: '400g',
            price: 400,
            img: 'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=270/app/images/products/sliding_image/86446a.jpg?ts=1641540332',
            amount: 1,
          },
        ],
    },
    {
        category: 'Clothing',
        items: [
            {
                id: 10,
                title: "Haldirams Punjabi Tadka Namkeen",
                weight: "220g",
                price: 54,
                img:"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/assets/products/sliding_images/jpeg/87199d95-d68a-49e0-8644-3695381d7faa.jpg?ts=1707313057" ,
                amount: 1,
              },
              {
                id: 11,
                title: "Doritos",
                weight: "2 X 82.5g",
                price: 100,
                img: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/full_screen/pro_381269.jpg?ts=1710346474",
                amount: 1,
              },
              {
                id: 12,
                title: "Haldiram Punjabi Masalas Papad",
                weight: "200g",
                price: 54,
                img: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/assets/products/sliding_images/jpeg/a40c0647-6a2f-45f9-a924-1873c4e0de87.jpg?ts=1707313057",
                amount: 1,
              },
              {
                id: 13,
                title: "Uncle Chips",
                weight: "50g",
                price: 20,
                img: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/11150a.jpg?ts=1688463551",
                amount: 1,
              },
              {
                id: 14,
                title: "Haldiram Lite Miixture Namkeen",
                weight: "150g",
                price: 35,
                img: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/19251a.jpg?ts=16879483",
                amount: 1,
              },
              {
                id: 15,
                title: "Lays Indias Magic",
                weight: "40g",
                price: 20,
                img: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/240092a.jpg?ts=1687324818",
                amount: 1,
              },
              {
                id: 16,
                title: "Haldiram Boondi",
                weight: "225g",
                price: 52,
                img: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/81953a.jpg?ts=1688972660",
                amount: 1,
              },
              {
                id: 17,
                title: "Masala Kurkure",
                weight: "200g",
                price: 40,
                img: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/67372a.jpg?ts=1697561896",
                amount: 1,
              },
        ],
    },
    
];
export default data;